### ISSUE TITLE
PollutionHandler

### ISSUE THREAD

**Issue by re7gog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1074]
Why server continues spamming this error?

[19:53:45 WARN]: java.io.IOException: Системе не удается найти указанный путь
[19:53:45 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[19:53:45 WARN]:        at java.io.File.createNewFile(File.java:1023)
[19:53:45 WARN]:        at com.hbm.handler.pollution.PollutionHandler.onWorldSave(PollutionHandler.java:126)
[19:53:45 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_159_PollutionHandler_onWorldSave_Save.invoke(.dynamic)
[19:53:45 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[19:53:45 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[19:53:45 WARN]:        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1096)
[19:53:45 WARN]:        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:533)
[19:53:45 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:866)
[19:53:45 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
[19:53:45 WARN]:        at java.lang.Thread.run(Thread.java:750)

**Comment by BallOfEnergy1** [comment]
It looks like the pollution handler can't find the pollution data (hbmpollution.dat) file. (For anyone not wanting to translate the russian text, it says "System cannot find the file specified.")

**Comment by HbmMods** [comment]
Does this happen all the time or only the first time you opened the world? Does your world folder have folders called "DIM" with the dimension ID in it?

**Comment by re7gog** [comment]
It happens all the time. I made some research and it looks like it's Crucible issue (Thermos fork). There is no hbmpollution.dat file in DIM1 and other dimensions folders like in Forge server, but there is hbmauxdata.dat.

**Comment by HbmMods** [comment]
Might be fixed in X4641, if it still happens it should now also add some more info on what exact folder it is it's trying to write to

**Comment by re7gog** [comment]
It's fixed now

**Comment by re7gog** [comment]
Well, actually it's not completely fixed, because with a high level of soot (~150) there is no visible smog

**Comment by re7gog** [comment]
And there is still no hbmpollution.dat file in DIM subfolders
