### ISSUE TITLE
i need help i don't know what the cause of the crash is 

### ISSUE THREAD

**Issue by beheadingtime3434** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1076]
java.lang.NullPointerException
    at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:400)
    at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:393)
    at com.hbm.render.RenderHelper.getItemTexture(RenderHelper.java:186)
    at com.hbm.render.RenderHelper.getItemTexture(RenderHelper.java:178)
    at com.hbm.render.RenderHelper.getItemTexture(RenderHelper.java:182)
    at com.hbm.render.entity.TSmokeRenderer.<init>(TSmokeRenderer.java:31)
    at com.hbm.render.entity.TSmokeRenderer.lambda$static$0(TSmokeRenderer.java:23)
    at com.hbm.render.entity.TSmokeRenderer$$Lambda$1934/1832067592.createRenderFor(Unknown Source)
    at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
    at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.call(Reflector.java:808)
    at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
    at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:276)
    at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
    at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at gg.essential.loader.stage1.EssentialLoader.load(EssentialLoader.java:125)
    at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:35)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:111)
    at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:34)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by burningwater202** [comment]
Is this the full crash report or just partial?

**Comment by beheadingtime3434** [comment]
> Is this the full crash report or just partial?

partial i can send the full one if you want

**Comment by beheadingtime3434** [comment]
but also i realize that the mod i'm using is Hbm's Nuclear Tech - Extended Edition so i'm gonna go to that github instead my bad
