### ISSUE TITLE
Game crashes on start

### ISSUE THREAD

**Issue by brambora69123** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1122]
### Describe the bug

Happens after I start the game, it does open for a while and loads mods in the phase 1, as it transitions to phase 2 it crashes.

Crash log:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 23.7.23 23:21
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/hbm/blocks/generic/BlockBedrockOreTE
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/hbm/blocks/generic/BlockBedrockOreTE
	at com.hbm.blocks.ModBlocks.initializeBlock(ModBlocks.java:1332)
	at com.hbm.blocks.ModBlocks.mainRegistry(ModBlocks.java:45)
	at com.hbm.main.MainRegistry.PreLoad(MainRegistry.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.hbm.blocks.generic.BlockBedrockOreTE
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 517029560 bytes (493 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCH	customnpcs{1.7} [CustomNPC+] (CustomNPC-Plus-1.7.jar) 
	UCH	flansmod{LabJac Mod Mark 25843 - February 2021} [Flan's Mod LabJac Edition] (flansmod_OHIO_public_sigma.jar) 
	UCH	wolffsmod{3.0} [Flan's Mod NPC Vehicles] (1.7.10FlansModNPCVehicles-3.0.jar) 
	UCH	npcflancompatibility{1.0} [CustomNPCs Flan Compatibility Mod] (1.7.10FlansModNPCVehicles-3.0.jar) 
	UCH	BetterPing{1.0} [Better Ping] (BetterPing-1.7.10-1.0.jar) 
	UCH	Eln{1.21.3} [Electrical Age - jrddunbr's build] (Eln-1.21.3.jar) 
	UCH	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UCH	hfr{LabCat} [Austria Hungary Mod] (flansmod_OHIO_public_sigma.jar) 
	UCE	hbm{1.0.27 BETA (4627)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4627].jar) 
	UCH	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-fairplay.jar) 
	UCH	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCH	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.02.19 30.0.13002.19003' Renderer: 'AMD Radeon(TM) Graphics'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.30.02.19 30.0.13002.19003
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
```

**Comment by JackyF737** [comment]
how did you fix this? I am having same issue with Flans Mod LabJac Edition
