### ISSUE TITLE
Server crashing due to world event handler tick

### ISSUE THREAD

**Issue by WhyDidYouSearchThis** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1341]
Server crashing due to a tick taking longer than 60 seconds
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at com.hbm.main.ModEventHandler.worldTick(ModEventHandler.java:733)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_346_ModEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by HbmMods** [comment]
The server shut off because a single tick got stuck for a full minute, that usually means there's some sort of (near) endless loop somewhere. That part of the code is responsible for the following things:
* Radiation debuffs
* Train movement
* Boss and meteor spawns
* Delayed spawning for jungle dungeons
* Anything related to siege mode

Did you change any configs regarding any of these things? What were you doing while it happened?
