### ISSUE TITLE
[X4977] Game crash in loading screen

### ISSUE THREAD

**Issue by Ranavolio** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1509]
I am trying the foolish endeavor of adding HBM into Divine Journey (1). It crashes when loading on the last steps, and cant figure out why. It only happens when HBM is enabled. It does not happen when trying to load it on a clean instance with only HBM. The main error is "The following texture errors were found.".

Log: https://paste.atlauncher.com/view/bd3b1b83-7a14-497e-b2ce-be1319a34ac2

**Comment by HbmMods** [comment]
Texture errors can't actually cause the game to crash and are fairly common and harmless. The log doesn't seem to mention a crash at all.

**Comment by Voxelstice** [comment]
a quick look at the log myself and it does mention a crash
```
[27/05/2024 21:26:29 PM] // Hey, that tickles! Hehehe!
[27/05/2024 21:26:29 PM] 
[27/05/2024 21:26:29 PM] Time: 5/27/24 9:26 PM
[27/05/2024 21:26:29 PM] Description: There was a severe problem during mod loading that has caused the game to fail
[27/05/2024 21:26:29 PM] 
[27/05/2024 21:26:29 PM] cpw.mods.fml.common.LoaderException: java.lang.RuntimeException: Invalid id 9539 - maximum id range exceeded.
[27/05/2024 21:26:29 PM] 	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[27/05/2024 21:26:29 PM] 	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
[27/05/2024 21:26:29 PM] 	at com.rwtema.denseores.DenseOresRegistry.buildBlocks(DenseOresRegistry.java:41)
[27/05/2024 21:26:29 PM] 	at com.rwtema.denseores.DenseOresMod.init(DenseOresMod.java:34)
...
[27/05/2024 21:26:29 PM] Caused by: java.lang.RuntimeException: Invalid id 9539 - maximum id range exceeded.
[27/05/2024 21:26:29 PM] 	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:379)
[27/05/2024 21:26:29 PM] 	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:894)
[27/05/2024 21:26:29 PM] 	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:869)
```
the dense ores mod or whatever exceeded the maximum range of block ids

**Comment by Ranavolio** [comment]
This seems to not have been the issue.

The issue seems to be a simple potion ID conflict that for some reason did not show in the ATLauncher log. It was showing in the log in the folder tho. Now with the potion IDs fixed it loads.
