### ISSUE TITLE
Crash due to java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by LekKit** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1563]
### Describe the bug

Random crash on worldgen.

```java
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.hbm.world.generator.CellularDungeon.generate(CellularDungeon.java:69)
	at com.hbm.lib.HbmWorldGen.generateSurface(HbmWorldGen.java:576)
	at com.hbm.lib.HbmWorldGen.generate(HbmWorldGen.java:66)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
[crash-2024-07-01_18.38.45-server.txt](https://github.com/user-attachments/files/16056666/crash-2024-07-01_18.38.45-server.txt)

### Mod version

HBM NTM 1.7.10 X5012

**Comment by fbfnysnshnsgnwg** [comment]
looks like worldgen bug

**Comment by HbmMods** [comment]
Seems to be two cellular dungeons colliding which is usually incredibly rare (meteorite dungeons only spawn in like 1:15k chunks anyway), still there's probably a way to prevent that.

**Comment by LekKit** [comment]
> Seems to be two cellular dungeons colliding which is usually incredibly rare (meteorite dungeons only spawn in like 1:15k chunks anyway), still there's probably a way to prevent that.

I had similar crashes on a Crucible public server where different structures were mentioned in crash log (don't remember which).
