### ISSUE TITLE
Automatic Crafting Table Bug

### ISSUE THREAD

**Issue by Sr-Anonymus-maker** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1585]
This happens in version 1.0.27 (5026), the game crashes if the Automatic Crafting Table has an conveyor ejector with a conveyor on one side and matches the guide recipe and the place where the items are placed for crafting.

![image](https://github.com/user-attachments/assets/acd321c1-698c-4b89-bcc6-a1df5e4f6c71)
![image](https://github.com/user-attachments/assets/37e2ffef-821a-4878-afe3-c5a2e3e9e8b2)
![image](https://github.com/user-attachments/assets/16aa2b5c-854e-4b77-a805-61f05f7d1f82)

The crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 14/07/24 05:42 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 10
	at com.hbm.module.ModulePatternMatcher.isValidForFilter(ModulePatternMatcher.java:122)
	at com.hbm.tileentity.machine.TileEntityMachineAutocrafter.func_102008_b(TileEntityMachineAutocrafter.java:194)
	at com.hbm.tileentity.network.TileEntityCraneExtractor.func_145845_h(TileEntityCraneExtractor.java:113)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.module.ModulePatternMatcher.isValidForFilter(ModulePatternMatcher.java:122)
	at com.hbm.tileentity.machine.TileEntityMachineAutocrafter.func_102008_b(TileEntityMachineAutocrafter.java:194)
	at com.hbm.tileentity.network.TileEntityCraneExtractor.func_145845_h(TileEntityCraneExtractor.java:113)

-- Block entity being ticked --
Details:
	Name: tileentity_extractor // com.hbm.tileentity.network.TileEntityCraneExtractor
	Block type: ID #1013 (tile.crane_extractor // com.hbm.blocks.network.CraneExtractor)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-483,4,-710), Chunk: (at 13,0,10 in -31,-45; contains blocks -496,0,-720 to -481,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Actual block type: ID #1013 (tile.crane_extractor // com.hbm.blocks.network.CraneExtractor)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['DUDE'/23, l='New World', x=-483.79, y=4.00, z=-711.42]]
	Chunk stats: ServerChunkCache: 957 Drop: 0
	Level seed: 9193034345272155579
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-491,4,-720), Chunk: (at 5,0,0 in -31,-45; contains blocks -496,0,-720 to -481,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 6120 game time, 6120 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 126639 (now: false), thunder time: 102609 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by HbmMods** [comment]
Fixed with X5027.
