### ISSUE TITLE
Damaged Howard turret crash

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1827]
### Describe the bug

Generated a new world using only latest HBM X5188, spawned a "Methusalem" turret, crashes upon shooting a cow or other mobs.

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/24/24 5:06 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.spawnCasing(TileEntityTurretBaseNT.java:893)
	at com.hbm.tileentity.turret.TileEntityTurretHowardDamaged.updateFiringTick(TileEntityTurretHowardDamaged.java:79)
	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.func_145845_h(TileEntityTurretBaseNT.java:226)
	at com.hbm.tileentity.turret.TileEntityTurretHoward.func_145845_h(TileEntityTurretHoward.java:127)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.spawnCasing(TileEntityTurretBaseNT.java:893)
	at com.hbm.tileentity.turret.TileEntityTurretHowardDamaged.updateFiringTick(TileEntityTurretHowardDamaged.java:79)
	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.func_145845_h(TileEntityTurretBaseNT.java:226)
	at com.hbm.tileentity.turret.TileEntityTurretHoward.func_145845_h(TileEntityTurretHoward.java:127)

-- Block entity being ticked --
Details:
	Name: tileentity_turret_howard_damaged // com.hbm.tileentity.turret.TileEntityTurretHowardDamaged
	Block type: ID #761 (tile.turret_howard_damaged // com.hbm.blocks.turret.TurretHowardDamaged)
	Block data value: 15 / 0xF / 0b1111
	Block location: World: (382,69,1108), Chunk: (at 14,4,4 in 23,69; contains blocks 368,0,1104 to 383,255,1119), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Actual block type: ID #761 (tile.turret_howard_damaged // com.hbm.blocks.turret.TurretHowardDamaged)
	Actual block data value: 15 / 0xF / 0b1111
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['W'/369, l='New World', x=384.66, y=70.00, z=1106.26]]
	Chunk stats: ServerChunkCache: 706 Drop: 0
	Level seed: 8591327471727598183
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (425,64,1092), Chunk: (at 9,4,4 in 26,68; contains blocks 416,0,1088 to 431,255,1103), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 748 game time, 748 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64524 (now: false), thunder time: 94058 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1987476704 bytes (1895 MB) / 2725249024 bytes (2599 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.4.0} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (5188)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X5188].jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	NTM Modified recipes:: 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['W'/369, l='New World', x=384.66, y=70.00, z=1106.26]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by bHXDgiuMa5yLHyC8** [comment]
Seems to happen with Howard CIWS too but not other turrets.
