### ISSUE TITLE
Crash with Better Questing

### ISSUE THREAD

**Issue by Crimento** [HbmMods/Hbm-s-Nuclear-Tech-GIT#294]
### Describe the bug

Having HBM's Nuclear Tech installed crashes Better Questing GUI when trying to change icon of questline or quest.
HBM's Nuclear Tech version: 1.0.27_X4000
Better Questing version: 3.0.328
Crash log: https://pastebin.com/ms6tV3ag

### Please solve this equation to x

x²+3x-19=√(9x²)+6
x = 5;
x = -3 - sqrt(34)

**Comment by HbmMods** [comment]
Seems like BQ is trying to render the custom missile item with a blank stack, although it assumes some NBT data which it needs to render correctly. I'll just add a clause where it renders a generic sprite when there's no NBT data.

**Comment by Crimento** [comment]
Sadly that doesn't help.

Here are the fresh logs on X4011, seems like error is the same:

But at least now I have time to choose something from inventory and close it before it crashes 🥲 
```
Time: 10/4/21 9:10 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.hbm.items.weapon.ItemCustomMissile.func_77624_a(ItemCustomMissile.java:62)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:57)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:21)
	at betterquesting.api2.client.gui.controls.PanelButtonStorage.<init>(PanelButtonStorage.java:14)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:40)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:30)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:85)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:17)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:247)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.items.weapon.ItemCustomMissile.func_77624_a(ItemCustomMissile.java:62)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:57)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:21)
	at betterquesting.api2.client.gui.controls.PanelButtonStorage.<init>(PanelButtonStorage.java:14)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:40)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:30)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:85)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:17)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:247)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
```

**Comment by Crimento** [comment]
@HbmMods fixed by last commit (https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/commit/639b2745b89893796da99780f5e7082f5a0ef09a), thanks!

Build version works fine, I'll wait for release and close the issue.

**Comment by HbmMods** [comment]
Newest build is out, closing this issue.
