### ISSUE TITLE
Crash allegedly associated with a gas mask overlay

### ISSUE THREAD

**Issue by luckybl0ck** [HbmMods/Hbm-s-Nuclear-Tech-GIT#305]
### Describe the bug

While playing on the server, the game client crashed with the following crash report.

> java.lang.ArrayIndexOutOfBoundsException: 6
	at com.hbm.items.armor.ArmorGasMask.renderHelmetOverlay(ArmorGasMask.java:115)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:253)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:117)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

https://hastebin.com/esimatucaq.yaml

**Mod version**: 1.0.27 BETA (3997)
**Forge version**: 10.13.4.1614

**Comment by HbmMods** [comment]
Fixed in the newest version.
