### ISSUE TITLE
Asteroid mining ship causes massive clientside lag during landing

### ISSUE THREAD

**Issue by thePalindrome** [HbmMods/Hbm-s-Nuclear-Tech-GIT#489]
Version 4158, the lag spike takes me from 24-40 to a nice, crunchy 1 fps

The lag spike seems to be in the `tick` namespace of all things

```
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root.tick.level.entities.regular.tick' took aprox 213.033293 ms
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root.tick.level.entities.regular' took aprox 214.804416 ms
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root.tick.level.entities' took aprox 216.64816 ms
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root.tick.level' took aprox 216.959027 ms
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root.tick' took aprox 519.528461 ms
[17:46:14] [Client thread/WARN]: Something's taking too long! 'root' took aprox 543.850774 ms
```

In addition, there's a  repeated network error (Not wanting to count, but we'll call it "over 60 times") locally regarding an NPE with:
```
at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210 [SimpleNetworkWrapper.class:?]
at com.hbm.explosion.ExplosionLarge.spawnShock(ExplosionLarge.java:51) [ExplosionLarge.class:?]
at com.hbm.entity.missile.EntityMinerRocket.func_70071_h_(EntityMinerRocket.java:60) [EntityMinerRocket.class:?]
```

The lag appears as the "body" contacts the pad and disappears when the rocket begins to ascend again, so that's presumably when it starts and stops spawning the "shock explosion".

As a side note that *might* be a red herring or *might* be related: a meteorite fell while I was watching for the mining ship to return, and it dipped me down from 40-ish to 20-ish, so there might be something funky with that kind of render.

**Comment by HbmMods** [comment]
Meteorites do spawn a ton of particles but those are mostly optimized so while that was probably a contributing factor, I'm putting my money on the constant log spam. Turns out something that should have only happened on the server is also happening on the client.

**Comment by HbmMods** [comment]
Log spam should be fixed, along with the lag assuming it was caused by said log spam. In either case the amount of particles should be lower too, I'm leaving the issue open as I haven't directly tested the mining ships yet.

**Comment by thePalindrome** [comment]
I haven't noticed too many issues with lag regarding that in particular, so I think we're in the clear!
