### ISSUE TITLE
Tried using hoppers for multipurpose bomb. Got this error

### ISSUE THREAD

**Issue by Joey-Destroyah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#50]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/8/20 1:19 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:312)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:277)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:205)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:190)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntityHopper.func_152102_a(TileEntityHopper.java:312)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:277)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:205)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:190)

-- Block entity being ticked --
Details:
	Name: Hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (3,66,472), Chunk: (at 3,4,8 in 0,29; contains blocks 0,0,464 to 15,255,479), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Joseph_da_IT_Guy'/215, l='New World', x=5.30, y=65.00, z=472.65]]
	Chunk stats: ServerChunkCache: 1420 Drop: 146
	Level seed: 2570333256247729242
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-252,64,248), Chunk: (at 4,4,8 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 29259 game time, 29259 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 138158 (now: false), thunder time: 25991 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 885158408 bytes (844 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	wizardry{1.1.5} [Electroblob's Wizardry] (Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (3493)} [Hbm's Nuclear Tech] (hbm_1.0.27_X3493.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist (1).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Joseph_da_IT_Guy'/215, l='New World', x=5.30, y=65.00, z=472.65]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by UFFR** [comment]
Why would you use a hopper with a bomb anyway? Even the crash report is wondering why.

**Comment by Joey-Destroyah** [comment]
For convenience sake. Welp, I guess thats what I get.

**Comment by UFFR** [comment]
The convenience of doing what? Wouldn't it just be easier to just put the things in manually rather than, from what I presume, is a long line of either hoppers or BuildCraft pipes just for one bomb? It's not like you can pick up this bomb and keep the internal components inside and try to mass-produce them.

**Comment by HbmMods** [comment]
Bombs have no hopper implementation, so even if it didn't crash, it would not do anything. The crash will be fixed in the next release.

**Comment by Joey-Destroyah** [comment]
I wish they had hoppers. It would be more convienient to set up, say a massive cluster bomb.

**Comment by HbmMods** [comment]
I fail to see how using a hopper is any easier than just inserting 6 items into a regular inventory of a block that you're only going to interact with once before blowing it up.

**Comment by UFFR** [comment]
Can you at least properly explain what you are attempting to do with multipurpose bombs and hoppers?
