### ISSUE TITLE
Crashing after updating from 1.0.27_X4152 to 1.0.27_X4158 during the initialization process!

### ISSUE THREAD

**Issue by gengyunmaster** [HbmMods/Hbm-s-Nuclear-Tech-GIT#500]
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter id= 1482359128 hashCode= 46 toString= cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@1482359128{m:0, i:net.minecraft.item.ItemMultiTexture@111105514, v:12}; object #2 =class cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter id= 1441653652 hashCode= 86376 toString= cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@1441653652{m:0, i:net.minecraft.item.ItemMultiTexture@111105514, v:12}

	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.set.hash.THashSet.rehash(THashSet.java:172)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.set.hash.THashSet.add(THashSet.java:112)
	at cofh.thermalexpansion.util.crafting.SmelterManager.addTERecipe(SmelterManager.java:316)
	at cofh.thermalexpansion.util.crafting.SmelterManager.addDefaultRecipes(SmelterManager.java:133)
	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by HbmMods** [comment]
According to the stacktrace you've posted, the crash is caused by Thermal Expansion. Could you try downgrading NTM to make sure it's the update that causes this? Did you change any config options on Thermal's side? What about a full crash log and mod list? The last version of NTM was tested on a server running a medium-sized modpack including Thermal Expansion and it worked just fine.

**Comment by gengyunmaster** [comment]
NTM 4152 can work properly with my modpack. I did not change any config of TE, just updated NTM form 4152 to 4158 and my game crashed. I don't know what happen... I would appreciate it if you could give me some suggestions. full crash-report and modlist can be found in attach files. Thank you!
[crash-2022-03-10_19.58.26-client.txt](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8223988/crash-2022-03-10_19.58.26-client.txt)
[loadedmod.csv](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8223991/loadedmod.csv)

**Comment by HbmMods** [comment]
The crash seems to occur right as TE is trying to load the default recipe of the smelter, or more precisely the primary input of four blocks of netherrack in the netherbrick smelting recipe. The last update hasn't changed anything in regards to those ingredients or interacted with any of Thermal's recipes, much rather I suspect it's one of your coremods that might be doing something weird. Could you try to launch the game just with TE, NTM and NEI (all with dependencies ofc)?

**Comment by gengyunmaster** [comment]
Yes, I can launch the game with TE, NTM and NEI... Maybe no one knows what's going on... Will I continue to use the old version 4152?... Or can I send you the complete modpack, which may help you further troubleshoot specific problems?

**Comment by HbmMods** [comment]
You could try taking out coremods, so things like the ones at the top of the list you've sent:
![image](https://user-images.githubusercontent.com/16674258/157721982-c430674a-eeba-4307-95b6-019a473cefda.png)
Since coremods often use bytecode manipulation that can lead to seemingly random issues like that if done wrong, I'd say one of those might be the most likely offender. In the meantime I'll read through TE's code, perhaps there's something else I can do.

**Comment by gengyunmaster** [comment]
OK... I will try to check and let you know if I can get the result. Anyway, thank you for your help!

**Comment by solundev** [comment]
i have his same issue without his mod conflict, already said it in discussions tab

**Comment by Shibva** [comment]
CoFH core is not an issue, I have that running on its own without the thermal mod

**Comment by gengyunmaster** [comment]
The previous crash problem disappeared after I updated to version 4193. Now my game with the modlist in attach file can work properly. Although we are not sure what the problem was before, thank you for your help anyway.
[loadedmod.csv](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/files/8456445/loadedmod.csv)
