### ISSUE TITLE
Errors with DecoBlock

### ISSUE THREAD

**Issue by Paneedah** [HbmMods/Hbm-s-Nuclear-Tech-GIT#517]
Not much additional information to provide other than the error seen in console.
It's pretty random when it appears in my server console.

Running version: 1.0.27_X3493

Error:
`[13:40:46 ERROR]: A TileEntity type com.hbm.tileentity.deco.TileEntityDecoBlockAltF has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.hbm.tileentity.deco.TileEntityDecoBlockAltF is missing a mapping! This is a bug!
        at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:92) ~[aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:393) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:220) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:416) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:497) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1091) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:538) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:866) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]`

**Comment by Paneedah** [comment]
Nevermind, noticed how outdated of a version my half-brained friend is using.
