### ISSUE TITLE
Server crash while starting

### ISSUE THREAD

**Issue by Kheeto** [HbmMods/Hbm-s-Nuclear-Tech-GIT#586]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/25/22 10:15 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.hbm.tileentity.machine.TileEntityMachineRadar.entityJoinWorld(TileEntityMachineRadar.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_TileEntityMachineRadar_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraft.world.WorldServer.func_175650_b(WorldServer.java:1382)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:946)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:93)
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:133)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:104)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:98)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:152)
	at net.minecraft.world.World.func_72964_e(World.java:445)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:561)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:451)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
	at java.lang.Thread.run(Thread.java:748)

**Comment by burningwater202** [comment]
It looks like you’re running a Minecraft 1.12.2 server, if you are trying to use NTM x4214 in it then that’s your problem since it is ONLY for Minecraft 1.7.10, there is a 1.12.2 fork available but features and functions may be different in it since it’s a separate project. You can find it here: https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/releases

edit: Beaten to the punch by 39 seconds

**Comment by Kheeto** [comment]
i'm already using the 1.12.2 fork, and the server worked until it crashed and now i get this error when starting it

**Comment by burningwater202** [comment]
Got it, I had some morning brain and just thought you posted in the wrong area 

by the sound of it the crash is coming from a Radar tile entity, did you or someone else happen to place a radar before the server crashed? I don’t know what the solution to the issue would be for now but at least we can try to drill down to the cause

**Comment by Kheeto** [comment]
i placed a radar but the server crashed much later so i don't know if that's the reason
