### ISSUE TITLE
Crash with unnamed recipe

### ISSUE THREAD

**Issue by Granniesgotaids** [HbmMods/Hbm-s-Nuclear-Tech-GIT#632]
I put an unnamed recipe that crashed the game when I press shift into my hot bar to dispose of it, by accident I put it in my hand and now the game crashes whenever I open it. My world is now stuck in a crash loop whenever I open the game

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/19/22 10:10 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at com.hbm.items.machine.ItemAssemblyTemplate.func_77653_i(ItemAssemblyTemplate.java:101)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at com.hbm.items.machine.ItemAssemblyTemplate.func_77653_i(ItemAssemblyTemplate.java:101)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LST123'/336, l='MpServer', x=-106.48, y=72.62, z=179.29]]
	Chunk stats: MultiplayerChunkCache: 35, 44
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-96,64,244), Chunk: (at 0,4,4 in -6,15; contains blocks -96,0,240 to -81,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9765187 game time, 9971180 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityItemFrame['entity.ItemFrame.name'/97, l='MpServer', x=-128.94, y=72.50, z=183.50], EntityItemFrame['entity.ItemFrame.name'/98, l='MpServer', x=-128.94, y=71.50, z=183.50], EntityItemFrame['entity.ItemFrame.name'/99, l='MpServer', x=-128.94, y=72.50, z=184.50], EntityItemFrame['entity.ItemFrame.name'/100, l='MpServer', x=-128.94, y=73.50, z=183.50], EntityZombie['Zombie'/101, l='MpServer', x=-135.50, y=8.00, z=201.50], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/102, l='MpServer', x=-138.38, y=71.27, z=207.34], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/103, l='MpServer', x=-142.44, y=70.27, z=223.06], EntityItem['item.item.rottenFlesh'/138, l='MpServer', x=-126.13, y=49.13, z=172.38], GCEntityClientPlayerMP['LST123'/336, l='MpServer', x=-106.48, y=72.62, z=179.29], EntityItem['item.item.bone'/139, l='MpServer', x=-127.41, y=49.13, z=172.03], EntityCreeper['Creeper'/140, l='MpServer', x=-117.44, y=14.00, z=191.00], EntityMinecartChest['entity.MinecartChest.name'/207, l='MpServer', x=-105.50, y=25.50, z=232.13], SpiderPig['INCOMPLETE'/240, l='MpServer', x=-91.66, y=7.00, z=180.69], SkeletonPart['entity.MutantCreatures.SkeletonPart.name'/254, l='MpServer', x=-48.66, y=62.27, z=174.34]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575061136 bytes (548 MB) / 1140850688 bytes (1088 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal - Copy.jar) 
	UCHIJAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	dungeonmobs{4.1.3} [Dungeon Mobs] (Dungeon-Mobs-1.7.10.jar) 
	UCHIJAAAA	ExtraMobs{1.0.0} [ExtraMobs] (Extra-Mobs-Mod-1.7.10.zip) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCHIJAAAA	fgtXray{1.0.1.75} [Fgt X-Ray] (fgtXray-1.7.10-1.0.1.75.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504 (1).jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4263H1)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4263H1.jar) 
	UCHIJAAAA	imsm{1.7.10} [Instant Massive Structures Mod] (Instant-Massive-Structures-Mod-1.7.10 - Copy.jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAAAA	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2 (2).jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	XaeroMinimap{21.10.22} [Xaero's Minimap] (Xaeros_Minimap_21.10.22_Forge_1.7.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.84' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.84, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 431.84
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by HbmMods** [comment]
May have been fixed in the previous release, although I haven't tested it using broken templates yet.
