### ISSUE TITLE
Render Error , maybe

### ISSUE THREAD

**Issue by Herestmain** [HbmMods/Hbm-s-Nuclear-Tech-GIT#727]
### Describe the bug
It seems that the Render Error happened when I joined a world . I couln't see anything but a black or white screen . I tried updating the graphics driver or change the version of java to solve this problem but it didn't work . Curiously, the  game log on Cilent side did not throw rendering errors . The log is below

------------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_332, IBM Corporation
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09), Eclipse OpenJ9
	Memory: 45944560 bytes (43 MB) / 172556288 bytes (164 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 15 total; -Xoptionsfile=C:\Program Files\Semeru\jdk-8.0.332.9-openj9\jre\bin\default\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.3109' Renderer: 'Intel(R) HD Graphics 620'
[18:36:13] [Client thread/INFO]: Attempting early MinecraftForge initialization
[18:36:13] [Client thread/INFO]: MinecraftForge v10.13.4.1614 Initialized
[18:36:13] [Client thread/INFO]: Replaced 183 ore recipies
[18:36:14] [Client thread/INFO]: Completed early MinecraftForge initialization
[18:36:14] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[18:36:14] [Client thread/INFO]: Searching D:\MC\.minecraft\versions\1.7.10\mods for mods
[18:36:14] [Client thread/INFO]: Also searching D:\MC\.minecraft\versions\1.7.10\mods\1.7.10 for mods
[18:36:20] [Client thread/INFO]: Forge Mod Loader has identified 6 mods to load
[18:36:21] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, hbm] at CLIENT
[18:36:21] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, hbm] at SERVER
[18:36:22] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Hbm's Nuclear Tech
[18:36:22] [Client thread/INFO]: Processing ObjectHolder annotations
[18:36:22] [Client thread/INFO]: Found 341 ObjectHolder annotations
[18:36:22] [Client thread/INFO]: Identifying ItemStackHolder annotations
[18:36:22] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[18:36:22] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[18:36:22] [Client thread/INFO]: Let us celebrate the fact that the logger finally works again!
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.Gson.fromJson(Gson.java:815)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at net.minecraftforge.common.ForgeVersion$1.run(ForgeVersion.java:94)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	... 4 more
[18:36:35] [Client thread/INFO]: Searching for new versions...
[18:36:35] [Client thread/INFO]: Found version 1.0.27 BETA (4336)
[18:36:35] [Client thread/INFO]: Version checker ended.
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityAMSBase implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityAMSEmitter implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityAMSLimiter implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachineSeleniumEngine implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachineReactorLarge implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.bomb.TileEntityLaunchTable implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.bomb.TileEntityCompactLauncher implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntitySoyuzLauncher implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachinePlasmaHeater implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachineLargeTurbine implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntitySILEX implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachineRadiolysis implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityElectrolyser implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.TileEntityMachineChemfac implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKBoiler implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKOutgasser implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKCooler implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKHeater implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKInlet implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityRBMKOutlet implements the old interfaces but not IFluidConnector!
[18:36:35] [Client thread/ERROR]: com.hbm.tileentity.machine.rbmk.TileEntityHeatex implements the old interfaces but not IFluidConnector!
[18:36:36] [Client thread/INFO]: Applying holder lookups
[18:36:36] [Client thread/INFO]: Holder lookups applied
[18:36:36] [Client thread/INFO]: Injecting itemstacks
[18:36:36] [Client thread/INFO]: Itemstack injection complete
[18:36:36] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:36] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[18:36:36] [Thread-12/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[18:36:36] [Thread-12/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:36:36] [Thread-12/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[18:36:36] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:36] [Sound Library Loader/INFO]: Sound engine started
[18:36:39] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[18:36:39] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[18:36:39] [Client thread/ERROR]: Unable to do mod description scrolling due to lack of stencil buffer
[18:36:39] [Client thread/ERROR]: Unable to do mod description scrolling due to lack of stencil buffer
[18:36:39] [Client thread/INFO]: Re-registration for ingotPolymer to ingotAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for dustPolymer to dustAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for blockPolymer to blockAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for ingotBakelite to ingotAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for dustBakelite to dustAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for blockBakelite to blockAnyPlastic
[18:36:39] [Client thread/INFO]: Re-registration for oiltar to anyTar
[18:36:39] [Client thread/INFO]: Re-registration for cracktar to anyTar
[18:36:39] [Client thread/INFO]: Re-registration for coaltar to anyTar
[18:36:39] [Client thread/INFO]: Injecting itemstacks
[18:36:39] [Client thread/INFO]: Itemstack injection complete
[18:36:39] [Client thread/INFO]: Starting recipe init!
[18:36:39] [Client thread/INFO]: No recipe file found, registering defaults for hbmChemplant.json
[18:36:39] [Client thread/INFO]: Writing template file _hbmChemplant.json
[18:36:39] [Client thread/INFO]: No recipe file found, registering defaults for hbmCentrifuge.json
[18:36:39] [Client thread/INFO]: Writing template file _hbmCentrifuge.json
[18:36:40] [Client thread/INFO]: No recipe file found, registering defaults for hbmCyclotron.json
[18:36:40] [Client thread/INFO]: Writing template file _hbmCyclotron.json
[18:36:40] [Client thread/INFO]: No recipe file found, registering defaults for hbmHadronCollider.json
[18:36:40] [Client thread/INFO]: Writing template file _hbmHadronCollider.json
[18:36:40] [Client thread/INFO]: No recipe file found, registering defaults for hbmFuelpool.json
[18:36:40] [Client thread/INFO]: Writing template file _hbmFuelpool.json
[18:36:40] [Client thread/INFO]: Finished recipe init!
[18:36:40] [Client thread/INFO]: Forge Mod Loader has successfully loaded 6 mods
[18:36:40] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Hbm's Nuclear Tech
[18:36:41] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[18:36:42] [Client thread/INFO]: Created: 1024x1024 textures/items-atlas
[18:36:43] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:43] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[18:36:43] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[18:36:43] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:43] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:43] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[18:36:43] [Thread-15/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[18:36:43] [Thread-15/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:36:43] [Client thread/ERROR]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[18:36:43] [Client thread/ERROR]: The following texture errors were found.
[18:36:43] [Client thread/ERROR]: ==================================================
[18:36:43] [Client thread/ERROR]:   DOMAIN hbm
[18:36:43] [Client thread/ERROR]: --------------------------------------------------
[18:36:43] [Client thread/ERROR]:   domain hbm is missing 12 textures
[18:36:43] [Client thread/ERROR]:     domain hbm has 1 location:
[18:36:43] [Client thread/ERROR]:       mod hbm resources at D:\MC\.minecraft\versions\1.7.10\mods\HBM-NTM-.1.0.27_X4336.jar
[18:36:43] [Client thread/ERROR]: -------------------------
[18:36:43] [Client thread/ERROR]:     The missing resources for domain hbm are:
[18:36:43] [Client thread/ERROR]:       textures/items/gun_thompson.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_spas12.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_flechette.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_flamer.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_ar15.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_bolter.png
[18:36:43] [Client thread/ERROR]:       textures/blocks/boat.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_bolter_digamma.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_bio_revolver.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_vortex.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_brimstone.png
[18:36:43] [Client thread/ERROR]:       textures/items/gun_fireext.png
[18:36:43] [Client thread/ERROR]: -------------------------
[18:36:43] [Client thread/ERROR]:     No other errors exist for domain hbm
[18:36:43] [Client thread/ERROR]: ==================================================
[18:36:43] [Client thread/ERROR]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[18:36:43] [Thread-15/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[18:36:43] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:36:43] [Sound Library Loader/INFO]: Sound engine started
[18:40:33] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[18:40:33] [Server thread/INFO]: Generating keypair
[18:40:33] [Server thread/INFO]: Converting map!
[18:40:33] [Server thread/INFO]: Scanning folders...
[18:40:33] [Server thread/INFO]: Total conversion count is 0
[18:40:33] [Server thread/INFO]: Injecting existing block and item data into this server instance
[18:40:34] [Server thread/INFO]: Applying holder lookups
[18:40:34] [Server thread/INFO]: Holder lookups applied
[18:40:35] [Server thread/INFO]: Loading dimension 0 (新的世界) (net.minecraft.server.integrated.IntegratedServer@bcb6746f)
[18:40:35] [Server thread/INFO]: Loading dimension 1 (新的世界) (net.minecraft.server.integrated.IntegratedServer@bcb6746f)
[18:40:35] [Server thread/INFO]: Loading dimension -1 (新的世界) (net.minecraft.server.integrated.IntegratedServer@bcb6746f)
[18:40:35] [Server thread/INFO]: Preparing start region for level 0
[18:40:36] [Server thread/INFO]: Preparing spawn area: 81%
[18:40:36] [Server thread/INFO]: Changing view distance to 6, from 10
[18:40:37] [Netty Client IO #0/INFO]: Server protocol version 2
[18:40:37] [Netty IO #1/INFO]: Client protocol version 2
[18:40:37] [Netty IO #1/INFO]: Client attempting to join with 6 mods : CodeChickenCore@1.0.7.48,NotEnoughItems@1.0.5.120,hbm@1.0.27 BETA (4336),FML@7.10.99.99,Forge@10.13.4.1614,mcp@9.05
[18:40:37] [Netty IO #1/INFO]: Attempting connection with missing mods [] at CLIENT
[18:40:37] [Netty Client IO #0/INFO]: Attempting connection with missing mods [] at SERVER
[18:40:37] [Server thread/INFO]: [Server thread] Server side modded connection established
[18:40:37] [Client thread/INFO]: [Client thread] Client side modded connection established
[18:40:37] [Server thread/INFO]: Herestmain[local:E:a81796e9] logged in with entity id 50 at (102.5, 4.0, 1467.5)
[18:40:37] [Server thread/INFO]: Herestmain 加入了游戏
[18:40:38] [Client thread/INFO]: [CHAT] Loaded world with Hbm's Nuclear Tech Mod 1.0.27 BETA (4336) for Minecraft 1.7.10!
[18:40:47] [Server thread/INFO]: Saving and pausing game...
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/Overworld
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/Nether
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/The End
[18:41:05] [Server thread/INFO]: Saving and pausing game...
[18:41:05] [Server thread/INFO]: Saving chunks for level '新的世界'/Overworld
[18:41:05] [Server thread/INFO]: Saving chunks for level '新的世界'/Nether
[18:41:05] [Server thread/INFO]: Saving chunks for level '新的世界'/The End
[18:41:07] [Server thread/INFO]: Saving and pausing game...
[18:41:07] [Server thread/INFO]: Saving chunks for level '新的世界'/Overworld
[18:41:07] [Server thread/INFO]: Saving chunks for level '新的世界'/Nether
[18:41:07] [Server thread/INFO]: Saving chunks for level '新的世界'/The End

--------------------------------------------------------------------------------

I discovered that  when I turn the game perspective , it outputs the following information
----
[18:40:47] [Server thread/INFO]: Saving and pausing game...
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/Overworld
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/Nether
[18:40:47] [Server thread/INFO]: Saving chunks for level '新的世界'/The End
----

please help me to solve it , I really like this mod . Thank you. :)

**Comment by HbmMods** [comment]
Does it still happen when removing NTM? Apparently there's an increasingly common issue where under certain conditions, this always happens on 1.7.10 regardless of whether there's any mods installed.

**Comment by Herestmain** [comment]
I tried to remove all the mods, and this annoying problem still happens . Then I remove forge , 
this problem still occurs . It looks like something went wrong with the vanllia . But in higher version , this problem does not occur

**Comment by HbmMods** [comment]
Might be some of the libraries that get bundled with the game. What launcher are you using?

**Comment by Herestmain** [comment]
The HMCL

**Comment by Herestmain** [comment]
Maybe I should try to roll back one version of the graphics card driver .

**Comment by Herestmain** [comment]
It dose work . This problem may be caused by upgrading the graphics card driver . And this problem can be solved by rolling back to the previous graphics card driver version
