### ISSUE TITLE
Casting basins crash

### ISSUE THREAD

**Issue by re7gog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#767]
When I place and remove casting basin game crashes

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 13.10.22 16:48
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.hbm.items.machine.ItemScraps.create(ItemScraps.java:71)
	at com.hbm.blocks.machine.FoundryCastingBase.func_149749_a(FoundryCastingBase.java:136)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:240)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:278)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.items.machine.ItemScraps.create(ItemScraps.java:71)
	at com.hbm.blocks.machine.FoundryCastingBase.func_149749_a(FoundryCastingBase.java:136)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:240)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:278)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3c4962a2
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 339223000 bytes (323 MB) / 2348810240 bytes (2240 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 38 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.7.7+3d2bec9} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4375)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4375.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	OpenComputers{1.7.7+3d2bec9} [OpenComputers] (OpenComputers-MC1.7.10-1.7.7+3d2bec9-universal.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	MineFactoryReloaded: -[1.7.10]2.8.2B1-201
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	ThermalDynamics: -[1.7.10]1.2.1-172
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['re7gog'/38, l='Новый мир', x=621,16, y=4,00, z=363,29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by username90001** [comment]
biomes of plenty and tconstruct can cause it but about other modsl ike choco craft extra biomes or twilight forest i xd

**Comment by re7gog** [comment]
But i don't have tconstract and world type was superflat
I think that it's empty casting basin issue, because when it's filled with template everything works fine
or it's just because of optifine

**Comment by HbmMods** [comment]
There was a confirmed issue like this but it was fixed about 2 hours after the verson was initially uploaded. If you got the mod on the day the new version came out, just redownload and it should be fine. If not, could you show me the MD5/SHA1 of the mod file you have?

**Comment by re7gog** [comment]
Yes, files are different while versions are the same, thank you
