### ISSUE TITLE
xd null rocket shoting down matter overdrive supply spaceship results in crash 

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#796]
first thing that i did it is cause metastable uranium decay
after found funni matter overdrive supply spaceship and started trying destroy it wiht stinger and 4 rocket launcher
after i used nuclear stinger and after i used digamma rocket - null rocket that crashed in 5 - 20 secounds untill spear reached ship

crash report 

Description: Exception getting block type in world

java.lang.RuntimeException: Already decorating!!
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at net.minecraft.world.biome.BiomeGenPlains.func_76728_a(BiomeGenPlains.java:96)
	at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147453_f(World.java:3873)
	at net.minecraft.world.World.func_147475_p(World.java:2610)
	at net.minecraft.block.BlockContainer.func_149749_a(SourceFile:21)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.hbm.world.feature.SchistStratum.onDecorate(SchistStratum.java:55)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1329_SchistStratum_onDecorate_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:113)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at net.minecraft.world.biome.BiomeGenPlains.func_76728_a(BiomeGenPlains.java:96)
	at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at glenn.gasesframework.Implementation.getGas(Implementation.java:349)
	at glenn.gasesframework.common.block.BlockGas.func_149674_a(BlockGas.java:445)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at net.minecraft.world.biome.BiomeGenPlains.func_76728_a(BiomeGenPlains.java:96)
	at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (95,32,-423), Chunk: (at 15,2,9 in 5,-27; contains blocks 80,0,-432 to 95,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147453_f(World.java:3873)
	at net.minecraft.world.World.func_147475_p(World.java:2610)
	at net.minecraft.block.BlockContainer.func_149749_a(SourceFile:21)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.hbm.world.feature.SchistStratum.onDecorate(SchistStratum.java:55)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1329_SchistStratum_onDecorate_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:113)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at net.minecraft.world.biome.BiomeGenPlains.func_76728_a(BiomeGenPlains.java:96)
	at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (111,19,-405), Chunk: (at 15,1,11 in 6,-26; contains blocks 96,0,-416 to 111,255,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at glenn.gasesframework.Implementation.getGas(Implementation.java:349)
	at glenn.gasesframework.common.block.BlockGas.func_149674_a(BlockGas.java:445)

-- Block being ticked --
Details:
	Block type: ID #1394 (gf_gas.greenGas // glenn.gasesframework.common.block.BlockGas)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (112,19,-405), Chunk: (at 0,1,11 in 7,-26; contains blocks 112,0,-416 to 127,255,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
i cant open this world now it just crashes everytime

**Comment by HbmMods** [comment]
Completely unrelated to MatterOverdrive or null rockets, the world generator crashes while trying to played a gas block from whatever `glenn.gasesframework` is.
