### ISSUE TITLE
crash again idk

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#801]
i was just walking
crash report
Time: 11/9/22 4:58 AM
Description: Exception getting block type in world

java.lang.RuntimeException: Already decorating!!
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at ttftcuts.atg.ATGChunkProvider.func_73153_a(ATGChunkProvider.java:426)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147453_f(World.java:3873)
	at net.minecraft.world.World.func_147475_p(World.java:2610)
	at net.minecraft.block.BlockContainer.func_149749_a(SourceFile:21)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.hbm.world.feature.SchistStratum.onDecorate(SchistStratum.java:55)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1308_SchistStratum_onDecorate_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:113)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at ttftcuts.atg.ATGChunkProvider.func_73153_a(ATGChunkProvider.java:426)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:144)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at ttftcuts.atg.ATGChunkProvider.func_73153_a(ATGChunkProvider.java:426)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-603,27,543), Chunk: (at 5,1,15 in -38,33; contains blocks -608,0,528 to -593,255,543), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147453_f(World.java:3873)
	at net.minecraft.world.World.func_147475_p(World.java:2610)
	at net.minecraft.block.BlockContainer.func_149749_a(SourceFile:21)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.hbm.world.feature.SchistStratum.onDecorate(SchistStratum.java:55)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1308_SchistStratum_onDecorate_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:113)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at ttftcuts.atg.ATGChunkProvider.func_73153_a(ATGChunkProvider.java:426)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:144)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)

**Comment by username90001** [comment]
are u going to help?

**Comment by HbmMods** [comment]
Try the most recent release, I suspect the issue is was caused by schist strata generating and replacing certain types of blocks, which would cause a crash through cascading worldgen.

**Comment by username90001** [comment]
ok thank u
