### ISSUE TITLE
PLEASE HELP lithium ion battery crashes my world when i trying to open it

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#805]
when i open my world it crashes from l ion battery probaly
i tried to create new world but it crashed after some time too 
crash report 

Description: Ticking block entity

java.lang.ClassCastException: com.hbm.tileentity.machine.TileEntityDummy cannot be cast to com.hbm.tileentity.machine.storage.TileEntityMachineBattery
	at com.hbm.blocks.machine.MachineBattery.func_149749_a(MachineBattery.java:178)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147480_a(World.java:594)
	at com.hbm.tileentity.machine.TileEntityDummy.func_145845_h(TileEntityDummy.java:18)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.blocks.machine.MachineBattery.func_149749_a(MachineBattery.java:178)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147480_a(World.java:594)
	at com.hbm.tileentity.machine.TileEntityDummy.func_145845_h(TileEntityDummy.java:18)

-- Block entity being ticked --
Details:
	Name: tileentity_dummy // com.hbm.tileentity.machine.TileEntityDummy
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-8,117,-120), Chunk: (at 8,7,8 in -1,-8; contains blocks -16,0,-128 to -1,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	
	
	
	other crash

Description: Ticking block entity

java.lang.ClassCastException: com.hbm.tileentity.machine.TileEntityDummy cannot be cast to com.hbm.tileentity.machine.storage.TileEntityMachineBattery
	at com.hbm.blocks.machine.MachineBattery.func_149749_a(MachineBattery.java:178)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147480_a(World.java:594)
	at com.hbm.tileentity.machine.TileEntityDummy.func_145845_h(TileEntityDummy.java:18)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.blocks.machine.MachineBattery.func_149749_a(MachineBattery.java:178)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147480_a(World.java:594)
	at com.hbm.tileentity.machine.TileEntityDummy.func_145845_h(TileEntityDummy.java:18)

-- Block entity being ticked --
Details:
	Name: tileentity_dummy // com.hbm.tileentity.machine.TileEntityDummy
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-8,117,-120), Chunk: (at 8,7,8 in -1,-8; contains blocks -16,0,-128 to -1,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

@HbmMods help

**Comment by username90001** [comment]
i created another world and it crashed too because of this error but i didnot even placed any electric machines like batteries

**Comment by HbmMods** [comment]
Somehow one of your battery blocks has the tile entity of a dummy block, did you use any world editors or schematics recently?

**Comment by username90001** [comment]
downloaded new mods?

**Comment by username90001** [comment]
new mods are  blank planet, mine together, parrarel world, end globules, endgame materials, infinity coblestone generators 
i have around 180 mods so there is only new mods after that crashes happening

**Comment by HbmMods** [comment]
Use McEdit or a comparable world editor to remove the tile entity at X:-8 Y:117 Z:-120.

**Comment by username90001** [comment]
i cant it crashes when i join world instantly

**Comment by HbmMods** [comment]
External editors don't require you to join the world.

**Comment by Howdidibreakit** [comment]
You shouldn't open lithium Ion Batteries, the lithium could ignite in the air due to moisture.

**Comment by username90001** [comment]
genius

**Comment by Howdidibreakit** [comment]
Also this is another ticking block entity bug that happens when you add new mods. I think it happens because it changes the block id's of the HBM stuff, and some blocks really don't like that.

**Comment by username90001** [comment]
ok
