### ISSUE TITLE
why my minecraft crashes everyday

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#817]
i left world and somehow got crash wth
crash log
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at matteroverdrive.starmap.GalaxyServer.onWorldSave(GalaxyServer.java:287)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1141_GalaxyServer_onWorldSave_Save.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:810)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:181)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by HbmMods** [comment]
`matteroverdrive.starmap.GalaxyServer.onWorldSave`

Matter Overdrive crashes during saving some world data.
