### ISSUE TITLE
Held item glitch

### ISSUE THREAD

**Issue by Kixxerin** [HbmMods/Hbm-s-Nuclear-Tech-GIT#880]
I used to play HBM before and recently reinstalled curse forge to play it again but keep running into issues with a zoom effect every time I pull out an item.
Ive tried deleting/reinstalling, changing memory allocation, and switching game and mod versions but I haven't had any luck fixing it, I'm currently running only HBM with no other active mods or texture packs but still getting the glitch.
I dont know if this would affect anything, but i did swap computers a while back. Since ive got the new PC it hasn't run while the last computer i had was able to run it. Computer specs are:
Processor	12th Gen Intel(R) Core(TM) i7-12700   2.10 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
GPU: GeForce RTX 3060
        Driver: 527.37
Monitor Display: 1920 x 1080 (60Hz)

In detail: When i load into a game the world seems to load random chunks and not load others. The grass blocks in the unloaded chunks appear as completely green, texture-less blocks and all entities in loaded or unloaded chunks are completely black. If im not holding an item in my hand my vision is normal, yet if i hold an item the world seems to "Zoom in" and my screen is entirely the color of the block i am currently looking at

Im using mod version 1.0.27_X4476
MC Version 1.7.10
CurseForge Version 10.13.4.1614 on Release

Here's the debug info if it helps:
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556683832 bytes (530 MB) / 751828992 bytes (717 MB) up to 3251109888 bytes (3100 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3488m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.3358' Renderer: 'Intel(R) UHD Graphics 770'
[12:07:08] [Client thread/INFO]: Attempting early MinecraftForge initialization
[12:07:08] [Client thread/INFO]: MinecraftForge v10.13.4.1614 Initialized
[12:07:08] [Client thread/INFO]: Replaced 183 ore recipies
[12:07:08] [Client thread/INFO]: Completed early MinecraftForge initialization
[12:07:08] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[12:07:08] [Client thread/INFO]: Searching C:\Users\slavi\curseforge\minecraft\Instances\HBM\mods for mods
[12:07:11] [Client thread/INFO]: Forge Mod Loader has identified 4 mods to load
[12:07:11] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, hbm] at CLIENT
[12:07:11] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, hbm] at SERVER
[12:07:11] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Hbm's Nuclear Tech
[12:07:11] [Client thread/INFO]: Processing ObjectHolder annotations
[12:07:11] [Client thread/INFO]: Found 341 ObjectHolder annotations
[12:07:11] [Client thread/INFO]: Identifying ItemStackHolder annotations
[12:07:11] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[12:07:11] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[12:07:11] [Client thread/INFO]: Let us celebrate the fact that the logger finally works again!
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:815)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.ForgeVersion$1.run(ForgeVersion.java:94)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[12:07:11] [Forge Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 4 more
[12:07:15] [Client thread/INFO]: Searching for new versions...
[12:07:15] [Client thread/INFO]: Found version 1.0.27 BETA (4476)
[12:07:15] [Client thread/INFO]: Version checker ended.
[12:07:15] [Client thread/ERROR]: [31mcom.hbm.tileentity.machine.TileEntityAMSBase implements the old interfaces but not IFluidConnector![0m
[12:07:15] [Client thread/ERROR]: [31mcom.hbm.tileentity.machine.TileEntityAMSEmitter implements the old interfaces but not IFluidConnector![0m
[12:07:15] [Client thread/ERROR]: [31mcom.hbm.tileentity.machine.TileEntityAMSLimiter implements the old interfaces but not IFluidConnector![0m
[12:07:15] [Client thread/ERROR]: [31mcom.hbm.tileentity.machine.TileEntityElectrolyser implements the old interfaces but not IFluidConnector![0m
[12:07:15] [Client thread/INFO]: Applying holder lookups
[12:07:15] [Client thread/INFO]: Holder lookups applied
[12:07:15] [Client thread/INFO]: Injecting itemstacks
[12:07:15] [Client thread/INFO]: Itemstack injection complete
[12:07:15] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:15] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[12:07:15] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[12:07:15] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[12:07:15] [Client thread/INFO]: Re-registration for ingotPolymer to ingotAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for dustPolymer to dustAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for blockPolymer to blockAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for ingotBakelite to ingotAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for dustBakelite to dustAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for blockBakelite to blockAnyPlastic
[12:07:15] [Client thread/INFO]: Re-registration for oiltar to anyTar
[12:07:15] [Client thread/INFO]: Re-registration for cracktar to anyTar
[12:07:15] [Client thread/INFO]: Re-registration for coaltar to anyTar
[12:07:15] [Client thread/INFO]: Re-registration for woodtar to anyTar
[12:07:15] [Thread-8/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[12:07:15] [Thread-8/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[12:07:15] [Client thread/INFO]: Injecting itemstacks
[12:07:15] [Client thread/INFO]: Itemstack injection complete
[12:07:15] [Client thread/INFO]: Starting recipe init!
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmShredder.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmShredder.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmChemplant.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmChemplant.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmCrucible.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmCrucible.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmCentrifuge.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmCentrifuge.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmLiquefactor.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmLiquefactor.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmSolidifier.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmSolidifier.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmCyclotron.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmCyclotron.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmHadronCollider.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmHadronCollider.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmFuelpool.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmFuelpool.json
[12:07:15] [Client thread/INFO]: No recipe file found, registering defaults for hbmCrucibleSmelting.json
[12:07:15] [Client thread/INFO]: Writing template file _hbmCrucibleSmelting.json
[12:07:15] [Client thread/INFO]: Finished recipe init!
[12:07:16] [Client thread/INFO]: Forge Mod Loader has successfully loaded 4 mods
[12:07:16] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Hbm's Nuclear Tech
[12:07:16] [Thread-8/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[12:07:16] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:16] [Sound Library Loader/INFO]: Sound engine started
[12:07:16] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[12:07:16] [Client thread/INFO]: Created: 1024x1024 textures/items-atlas
[12:07:16] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:16] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[12:07:17] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[12:07:17] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:17] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:17] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[12:07:17] [Client thread/ERROR]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[12:07:17] [Client thread/ERROR]: The following texture errors were found.
[12:07:17] [Client thread/ERROR]: ==================================================
[12:07:17] [Client thread/ERROR]:   DOMAIN minecraft
[12:07:17] [Client thread/ERROR]: --------------------------------------------------
[12:07:17] [Client thread/ERROR]:   domain minecraft is missing 6 textures
[12:07:17] [Client thread/ERROR]:     domain minecraft has 2 locations:
[12:07:17] [Client thread/ERROR]:       unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
[12:07:17] [Client thread/ERROR]:       mod hbm resources at C:\Users\slavi\curseforge\minecraft\Instances\HBM\mods\HBM-NTM-.1.0.27_X4476.jar
[12:07:17] [Client thread/ERROR]: -------------------------
[12:07:17] [Client thread/ERROR]:     The missing resources for domain minecraft are:
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_605_concrete_double_slab.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_606_concrete_brick_slab.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_608_brick_slab.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_607_concrete_brick_double_slab.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_604_concrete_slab.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/MISSING_ICON_BLOCK_609_brick_double_slab.png
[12:07:17] [Client thread/ERROR]: -------------------------
[12:07:17] [Client thread/ERROR]:     No other errors exist for domain minecraft
[12:07:17] [Client thread/ERROR]: ==================================================
[12:07:17] [Client thread/ERROR]: ==================================================
[12:07:17] [Client thread/ERROR]:   DOMAIN hbm
[12:07:17] [Client thread/ERROR]: --------------------------------------------------
[12:07:17] [Client thread/ERROR]:   domain hbm is missing 12 textures
[12:07:17] [Client thread/ERROR]:     domain hbm has 1 location:
[12:07:17] [Client thread/ERROR]:       mod hbm resources at C:\Users\slavi\curseforge\minecraft\Instances\HBM\mods\HBM-NTM-.1.0.27_X4476.jar
[12:07:17] [Client thread/ERROR]: -------------------------
[12:07:17] [Client thread/ERROR]:     The missing resources for domain hbm are:
[12:07:17] [Client thread/ERROR]:       textures/items/gun_thompson.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_spas12.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_flechette.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_flamer.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_ar15.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_bolter.png
[12:07:17] [Client thread/ERROR]:       textures/blocks/boat.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_bolter_digamma.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_bio_revolver.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_vortex.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_brimstone.png
[12:07:17] [Client thread/ERROR]:       textures/items/gun_fireext.png
[12:07:17] [Client thread/ERROR]: -------------------------
[12:07:17] [Client thread/ERROR]:     No other errors exist for domain hbm
[12:07:17] [Client thread/ERROR]: ==================================================
[12:07:17] [Client thread/ERROR]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[12:07:17] [Thread-10/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[12:07:17] [Thread-10/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[12:07:17] [Thread-10/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[12:07:17] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:17] [Sound Library Loader/INFO]: Sound engine started
[12:07:33] [Client thread/INFO]: Deleting level New World
[12:07:33] [Client thread/INFO]: Attempt 1...
[12:07:38] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[12:07:38] [Server thread/INFO]: Generating keypair
[12:07:38] [Server thread/INFO]: Converting map!
[12:07:38] [Server thread/INFO]: Scanning folders...
[12:07:38] [Server thread/INFO]: Total conversion count is 0
[12:07:38] [Server thread/INFO]: Injecting existing block and item data into this server instance
[12:07:38] [Server thread/INFO]: Applying holder lookups
[12:07:38] [Server thread/INFO]: Holder lookups applied
[12:07:39] [Server thread/INFO]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@28a8efdc)
[12:07:39] [Server thread/INFO]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@28a8efdc)
[12:07:39] [Server thread/INFO]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@28a8efdc)
[12:07:39] [Server thread/INFO]: Preparing start region for level 0
[12:07:39] [Server thread/INFO]: Changing view distance to 16, from 10
[12:07:40] [Netty Client IO #0/INFO]: Server protocol version 2
[12:07:40] [Netty IO #1/INFO]: Client protocol version 2
[12:07:40] [Netty IO #1/INFO]: Client attempting to join with 4 mods : hbm@1.0.27 BETA (4476),FML@7.10.99.99,Forge@10.13.4.1614,mcp@9.05
[12:07:40] [Netty IO #1/INFO]: Attempting connection with missing mods [] at CLIENT
[12:07:40] [Netty Client IO #0/INFO]: Attempting connection with missing mods [] at SERVER
[12:07:40] [Server thread/INFO]: [Server thread] Server side modded connection established
[12:07:40] [Server thread/INFO]: Drylical[local:E:ad28f635] logged in with entity id 0 at (-353.5, 4.0, -646.5)
[12:07:40] [Server thread/INFO]: Drylical joined the game
[12:07:40] [Client thread/INFO]: [Client thread] Client side modded connection established
[12:07:40] [Client thread/INFO]: [CHAT] Loaded world with Hbm's Nuclear Tech Mod 1.0.27 BETA (4476) for Minecraft 1.7.10!
[12:07:56] [Server thread/INFO]: Saving and pausing game...
[12:07:56] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[12:07:56] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[12:07:56] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[12:07:57] [Server thread/INFO]: Stopping server
[12:07:57] [Server thread/INFO]: Saving players
[12:07:57] [Server thread/INFO]: Saving worlds
[12:07:57] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[12:07:57] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[12:07:57] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[12:07:57] [Server thread/INFO]: Unloading dimension 0
[12:07:57] [Server thread/INFO]: Unloading dimension -1
[12:07:57] [Server thread/INFO]: Unloading dimension 1
[12:07:57] [Server thread/INFO]: Applying holder lookups
[12:07:57] [Server thread/INFO]: Holder lookups applied
[12:07:58] [Client thread/INFO]: Stopping!
[12:07:58] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 
[12:07:58] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[12:07:58] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[12:07:58] [Client thread/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: 

Pictured: World gen (The green blocks show unloaded chunks)
![Screenshot (4)](https://user-images.githubusercontent.com/122691046/212486972-c5d06503-742b-488c-bb50-a6753d7fd06e.png)

Entity Texture:
![Screenshot (5)](https://user-images.githubusercontent.com/122691046/212487013-52f9bdec-2c0e-4d10-9b38-33bf9dd655c8.png)

Looking at sky with empty hand:
![Screenshot (6)](https://user-images.githubusercontent.com/122691046/212487036-8cf45bf5-9d70-4f0e-98fa-84dc8c485fb0.png)
                Same view while holding a grass block:
![Screenshot (7)](https://user-images.githubusercontent.com/122691046/212487051-82615754-f511-478c-8ee0-7b00d3882281.png)
                While looking at the ground:    
![Screenshot (8)](https://user-images.githubusercontent.com/122691046/212487064-6e29a945-9bfa-4fc7-88f4-a80799555934.png)

**Comment by HbmMods** [comment]
`GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.3358' Renderer: 'Intel(R) UHD Graphics 770'`

This is a known issue for 1.7 in general from a faulty intel UHD driver, make sure you're actually running the game with your dedicated GPU.
