### ISSUE TITLE
planet and inventory bug

### ISSUE THREAD

**Issue by username90001** [HbmMods/Hbm-s-Nuclear-Tech-GIT#980]
i was on some planet from starminer in minceraft while going down in category with fuel and batteries and tanks i forgot name
when i go past rbmk depleted fuel my game crashes

Time: 3/31/23 10:32 PM
Description: Rendering screen

java.lang.ClassCastException: com.hbm.items.machine.ItemWatzPellet cannot be cast to com.hbm.items.machine.ItemRBMKRod
	at com.hbm.items.machine.ItemWatzPellet.getEnrichment(ItemWatzPellet.java:148)
	at com.hbm.items.machine.ItemWatzPellet.getDurabilityForDisplay(ItemWatzPellet.java:144)
	at com.hbm.items.machine.ItemWatzPellet.showDurabilityBar(ItemWatzPellet.java:139)
	at net.minecraft.client.renderer.entity.RenderItem.func_94148_a(RenderItem.java:691)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:490)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.items.machine.ItemWatzPellet.getEnrichment(ItemWatzPellet.java:148)
	at com.hbm.items.machine.ItemWatzPellet.getDurabilityForDisplay(ItemWatzPellet.java:144)
	at com.hbm.items.machine.ItemWatzPellet.showDurabilityBar(ItemWatzPellet.java:139)
	at net.minecraft.client.renderer.entity.RenderItem.func_94148_a(RenderItem.java:691)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:490)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (577, 308). Absolute: (1155, 401)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

**Comment by username90001** [comment]
i tried open and list it multiple times 100% crash

**Comment by BallOfEnergy1** [comment]
This is a known bug, as there have been tons of reports about this exact line:
"java.lang.ClassCastException: com.hbm.items.machine.ItemWatzPellet cannot be cast to com.hbm.items.machine.ItemRBMKRod"
A fix is probably on the way, it was caused by something in the new watz rework.

**Comment by HbmMods** [comment]
Fixed in X4561.

**Comment by username90001** [comment]
> Fixed in X4561.

ok
